# Generated by Django 3.2.5 on 2021-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_quote_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publihed',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
