# Generated by Django 3.2.5 on 2021-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210904_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_in',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
