# Generated by Django 3.2.5 on 2021-09-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book_read_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.book'),
        ),
    ]
