# Generated by Django 3.2.5 on 2021-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_author_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
