# Generated by Django 3.2.5 on 2021-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210904_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
